[project]
name = "textrpg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.6.7",
    "openai>=1.108.1",
    "pydantic>=2.11.9",
    "textual",
]
